### ISSUE TITLE
Running backtests using old ocf models.

### ISSUE THREAD

**Issue by zakwatts** [openclimatefix/uk-pv-backtest#22]
Instructions on how to backtest models previously trained using ocf_datapipes.

my existing conda (pvnet_v4) environment has (Python 3.11.9): 
- PVNet: v3.0.47
- ocf_datapipes: v3.3.37

**Steps to reproduce**
1. 3. creating my venv: `conda create -n pvnet_v5 python==3.11.9`
2. Activate env: `conda activate pvnet_v5`
3. Create a new folder. `mkdir pvnet_backtest_recreate`
4. Go into folder and clone PVNet repo at v3.0.47 `git clone -b v3.0.47 https://github.com/openclimatefix/PVNet/`
5. go into PVNet folder and install PVNet as an executable `pip install -e .`

Error: missing pvnet_app.
Fix: I've copied over the function from pvnet_app ` preds_to_dataarray` [here](https://github.com/openclimatefix/uk-pvnet-app/blob/8d0633976f414f4bc386e40fccebe8f6f3c15546/src/pvnet_app/forecast_compiler.py#L284) to avoid importing pvnet_app and added to backtest script.

Error: PVLive communication error
Fix: I've added in domain_url="api.pvlive.uk" to all instances of the PVLive class. (in the pvlive_api library) to fix this [here](https://github.com/SheffieldSolar/PV_Live-API/issues/53)

Error: I was getting this error:
``` 
checkpoint = torch.load(files[0], map_location="cpu")
Error executing job with overrides: []
Error locating target 'pvnet_summation.models.flat_model.FlatModel', set env var HYDRA_FULL_ERROR=1 to see chained exception.
```
Fix: Pvnet_summation repo needs to be installed by the looks of things: followed instructions [here](https://github.com/openclimatefix/PVNet-summation), install as an executable.

Error: `INFO:ocf_datapipes.training.common:Filled NaNs with zeros - {'BatchKey.gsp'}` 
Fix: Nothing! Just wait for it to go through each GSP. (takes around 20 minutes so far...)

Run into a strange satellite_actual issue after the above ran for around 15/20 minutes. 

****Need to reconfirm this next bit as turns out i didn't install v3.0.58 and stayed in 3.0.47 which ended up working okay
Going to try upgrade PVNet to: 5.0.58,
1. `git stash`
2. `git checkout v3.0.58` 

copy over the config.example.

create a new file called `backtest.yaml` located withing the configs.datamodule folder i.e `/home/zak/projects/pvnet_backtest_recreate/PVNet/configs/datamodule/backtest.yaml`

This files looks like:
```
_target_: pvnet.data.datamodule.DataModule
# Path to the data configuration yaml file. You can find examples in the configuration subdirectory
# in configs.example/datamodule/configuration
# Use the full local path such as: /FULL/PATH/PVNet/configs/datamodule/configuration/gcp_configuration.yaml"
configuration: "/home/zak/projects/pvnet_backtest_recreate/PVNet/configs/datamodule/configuration/data_config_intraday_backtest.yaml"
num_workers: 5
prefetch_factor: 2
batch_size: 4
```

Then update the `config.yaml` file to have `  - datamodule: backtest.yaml`.

This is what my `data_config_intraday_backtest.yaml` file looks like

```
general:
  description: Config for producing batches on GCP
  name: gcp_pvnet

input_data:
  default_history_minutes: 120
  default_forecast_minutes: 480

  gsp:
    gsp_zarr_path: /mnt/disks/uk-all-inputs-v3/pv_gsp/pvlive_gsp.zarr
    history_minutes: 120
    forecast_minutes: 480
    time_resolution_minutes: 30
    # A random value from the list below will be chosen as the delay when dropout is used
    # If set to null no dropout is applied. Only values before t0 are dropped out for GSP.
    # Values after t0 are assumed as targets and cannot be dropped.
    dropout_timedeltas_minutes: null
    dropout_fraction: 0 # Fraction of samples with dropout

  nwp:

    ukv:
        nwp_provider: ukv
        nwp_zarr_path:
          # - /mnt/disks/gcp_data/nwp/ukv/UKV_intermediate_version_7.1.zarr
          # - /mnt/disks/gcp_data/nwp/ukv/UKV_2021_missing.zarr
          # - /mnt/disks/gcp_data/nwp/ukv/UKV_2022.zarr
          # - /mnt/disks/gcp_data/nwp/ukv/ukv_ext/UKV_2022.zarr
          - /mnt/disks/uk-all-inputs-v3/nwp/ukv/UKV_v8/UKV_2023.zarr
          # - /mnt/disks/gcp_data/nwp/ukv/ukv_ext/UKV_2024.zarr
        history_minutes: 120
        forecast_minutes: 480
        time_resolution_minutes: 60
        nwp_channels:
        # These variables exist in the CEDA training set and in the live MetOffice live service
        - dlwrf # downwards long-wave radiation flux
        - dswrf # downwards short-wave radiation flux
        - hcc # high cloud cover
        - lcc # low cloud cover
        - mcc # medium cloud cover
        - prate # precipitation rate
        - r # relative humidty
        - sde # snow depth water equivalent
        - si10 # 10-metre wind speed
        - t # 2-metre temperature
        - vis # visibility
        nwp_image_size_pixels_height: 24
        nwp_image_size_pixels_width: 24
        dropout_timedeltas_minutes: [-180]
        dropout_fraction: 1.0
        max_staleness_minutes: 1080

    ecmwf:
        nwp_provider: ecmwf
        nwp_zarr_path:
          # - /mnt/disks/gcp_data/nwp/ecmwf/uk_ext/ECMWF_2017.zarr
          # - /mnt/disks/gcp_data/nwp/ecmwf/uk_ext/ECMWF_2018.zarr
          # - /mnt/disks/gcp_data/nwp/ecmwf/uk_ext/ECMWF_2019.zarr
          # - /mnt/disks/gcp_data/nwp/ecmwf/uk_ext/ECMWF_2020.zarr
          # - /mnt/disks/gcp_data/nwp/ecmwf/uk_ext/ECMWF_2021.zarr
          # - /mnt/disks/gcp_data/nwp/ecmwf/uk_ext/ECMWF_2022.zarr
          - /mnt/disks/uk-all-inputs-v3/nwp/ecmwf/UK_v3/ECMWF_2023.zarr
          # - /mnt/disks/gcp_data/nwp/ecmwf/uk_ext/ECMWF_2024.zarr
        history_minutes: 120
        forecast_minutes: 480
        time_resolution_minutes: 60

        nwp_channels:
        - t2m # 2-metre temperature
        - dswrf # downwards short-wave radiation flux
        - dlwrf # downwards long-wave radiation flux
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - tcc # total cloud cover
        - sd # snow depth water equivalent
        - sr # direct solar radiation
        - duvrs # downwards UV radiation at surface
        - u10 # 10-metre U component of wind speed
        - v10 # 10-metre V component of wind speed

        # The following channels are accumulated and need to be diffed
        nwp_accum_channels:
        - dswrf
        - dlwrf
        - sr
        - duvrs

        nwp_image_size_pixels_height: 12 # roughly equivalent to ukv 48
        nwp_image_size_pixels_width: 12 # roughly equivalent to ukv 48
        dropout_timedeltas_minutes: [-360]
        dropout_fraction: 1.0
        max_staleness_minutes: null

  satellite:
    satellite_zarr_path:
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-01_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-02_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-03_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-04_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-05_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-06_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-07_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-08_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-09_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-10_nonhrv.zarr
      - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-11_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2023-12_nonhrv_v2.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-01_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-02_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-03_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-04_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-05_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-06_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-07_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-08_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-09_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-10_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-11_nonhrv.zarr
      # - /mnt/disks/uk-all-inputs-v3/sat/v2/2024-12_nonhrv.zarr
    history_minutes: 90
    forecast_minutes: 0
    live_delay_minutes: 30 # 30 minutes delay for satellite data
    time_resolution_minutes: 5
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels_height: 24
    satellite_image_size_pixels_width: 24
    dropout_timedeltas_minutes: [-5,-10,-15]
    dropout_fraction: 0.2
```
